version: "3"
services:
  ruby-im-6: &ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.5.1
        IM_VERSION: 6
    volumes:
      - .:/app:cached
      - vendor-ruby:/vendor
      - home:/home/app
  ruby-im-7:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.5.1
        IM_VERSION: 7
volumes:
  ? home
  ? vendor-ruby
